<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 11</b></center>&nbsp;&nbsp;&nbsp;&nbsp;
<left><b><h3>Roll No. : 101</b></left>&nbsp;&nbsp;
<left><b><h3>Name :Bhojani Aastha </b></left>&nbsp;&nbsp;&nbsp;
<pre>

### 1. Create a MultiIndexed DataFrame

Create a DataFrame containing student marks for different Departments and Semesters. Use `set_index()` to create a MultiIndex using `Department` and `Semester`. Display the DataFrame and its index.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88],
    'Semester':[2,4,7,5]
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Semester'])
print(df)

### 2. Create a MultiIndex using Multiple Columns

Create a DataFrame containing `Department`, `Year`, `Gender`,`Student`and `Marks`. Set `Department`, `Year` and `Gender` as the MultiIndex and display the resulting DataFrame.

In [ ]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88]
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Year', 'Gender'])

print(df)

### 3. Read a MultiIndexed DataFrame Directly from CSV

Create a CSV file containing columns `Department`, `Semester`, `Subject`, and `Marks`. Read the CSV file directly as a MultiIndexed DataFrame using `pd.read_csv()` with the appropriate `index_col` parameter. Display the resulting DataFrame.

In [10]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88]
}

df=pd.DataFrame(data)

df.to_csv("dept.csv")

df1=pd.read_csv("dept.csv",index_col="Department")

df1

            Unnamed: 0  Year  Gender Student  Marks
Department
CS                   0  2023    Male    Amit     85
CS                   1  2023  Female   Priya     92
IT                   2  2024    Male   Rahul     78
IT                   3  2024  Female    Neha     88

### 4. Inspect a MultiIndexed DataFrame

Using the MultiIndexed DataFrame created in Question 3, display the index levels, index names, columns, shape, and data types.

In [13]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88]
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Year', 'Gender'])

print("Index Levels:")
print(df.index.levels)

print("\nIndex Names:")
print(df.index.names)

print("\nColumns:")
print(df.columns)

print("\nShape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

Index Levels:
[['CS', 'IT'], [2023, 2024], ['Female', 'Male']]

Index Names:
['Department', 'Year', 'Gender']

Columns:
Index(['Student', 'Marks'], dtype='object')

Shape:
(4, 2)

Data Types:
Student    object
Marks       int64
dtype: object

### 5. Access Data using MultiIndex

Using a MultiIndexed DataFrame having `Department` and `Semester` as indexes, access all records belonging to one department and one specific department-semester combination.

In [19]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88],
    'Semester':[2,4,7,5]
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Semester'])

print(df.loc[("CS", 2)])

Year       2023
Gender     Male
Student    Amit
Marks        85
Name: (CS, 2), dtype: object

### 6. Cross Section using xs()

Create a MultiIndexed DataFrame with `Department` and `Semester` as index levels. Use `xs()` to retrieve the records for a particular semester across all departments.

In [20]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88],
    'Semester':[2,4,7,5]
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Semester'])

print(df.xs(4, level='Semester'))

            Year  Gender Student  Marks
Department
CS          2023  Female   Priya     92

### 7. Cross Section from a Specific Level

Using the same MultiIndexed DataFrame, use `xs()` with the `level` parameter to retrieve records for one department. Display the result.

In [23]:
print(df.xs('CS', level='Department'))

          Year  Gender Student  Marks
Semester
2         2023    Male    Amit     85
4         2023  Female   Priya     92

### 8. Cross Section on Multiple Index Levels

Create a MultiIndexed DataFrame with `Department`, `Semester`, and `Subject` as index levels. Use `xs()` to retrieve the records corresponding to a particular combination of Department and Semester.

In [28]:
data = {
    'Department': ['CS', 'CS', 'IT', 'IT'],
    'Year': [2023, 2023, 2024, 2024],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Student': ['Amit', 'Priya', 'Rahul', 'Neha'],
    'Marks': [85, 92, 78, 88],
    'Semester':[2,4,7,5],
    'Subject':['IAT','DM','PDS','DOS']
}

df = pd.DataFrame(data)

df = df.set_index(['Department', 'Semester','Subject'])

result = df.xs(('CS', 2), level=['Department', 'Semester'])
print(result)

         Year Gender Student  Marks
Subject
IAT      2023   Male    Amit     85

### 9. Identify Missing Data

Create a student DataFrame containing `Name`, `Department`, `Marks`, `Attendance`, and `City`, with some missing values represented by `NaN` or `None`. Display the DataFrame and identify the missing values using `isna()`.

In [29]:
data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Karan'],
    'Department': ['CS', 'IT', None, 'CS', 'IT'],
    'Marks': [85, 92, np.nan, 88, 76],
    'Attendance': [90, None, 85, np.nan, 95],
    'City': ['Ahmedabad', 'Surat', 'Vadodara', None, 'Rajkot']
}

df = pd.DataFrame(data)

print("Student DataFrame:")
print(df)

print("\nMissing Values")
print(df.isna())

Student DataFrame:
    Name Department  Marks  Attendance       City
0   Amit         CS   85.0        90.0  Ahmedabad
1  Priya         IT   92.0         NaN      Surat
2  Rahul       None    NaN        85.0   Vadodara
3   Neha         CS   88.0         NaN       None
4  Karan         IT   76.0        95.0     Rajkot

Missing Values
    Name  Department  Marks  Attendance   City
0  False       False  False       False  False
1  False       False  False        True  False
2  False        True   True       False  False
3  False       False  False        True   True
4  False       False  False       False  False

### 10. Count Missing Values

Using the DataFrame from Question 9, calculate the number of missing values in each column and display the total number of missing values in the complete DataFrame.

In [30]:
print("Missing values in each column:")
print(df.isna().sum())

print("\nTotal missing values:")
print(df.isna().sum().sum())

Missing values in each column:
Name          0
Department    1
Marks         1
Attendance    2
City          1
dtype: int64

Total missing values:
5

### 11. Detect Missing Values using isnull()

Create a DataFrame containing missing values in different columns. Use `isnull()` and `notnull()` to display the missing and non-missing values. Compare the results of `isnull()` and `isna()`.

In [33]:
print(df.isnull().sum().sum())

print(df.isna())

print(df.isnull().equals(df.isna()))

5
    Name  Department  Marks  Attendance   City
0  False       False  False       False  False
1  False       False  False        True  False
2  False        True   True       False  False
3  False       False  False        True   True
4  False       False  False       False  False
True

### 12. Remove Missing Values

Using a DataFrame containing missing values, demonstrate `dropna()` to remove rows containing at least one missing value. Also demonstrate how to remove columns containing missing values.

In [36]:
df.dropna(axis = 1, inplace = False)

    Name
0   Amit
1  Priya
2  Rahul
3   Neha
4  Karan

### 13. Fill Missing Values with a Constant

Create a DataFrame containing missing values in the `Marks` and `City` columns. Replace missing values using suitable constant values with `fillna()`.

In [38]:
data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Karan'],
    'Department': ['CS', 'IT', None, 'CS', 'IT'],
    'Marks': [85, 92, np.nan, 88, 76],
    'Attendance': [90, None, 85, np.nan, 95],
    'City': ['Ahmedabad', 'Surat', 'Vadodara', None, 'Rajkot']
}

df = pd.DataFrame(data)

df['Marks'] = df['Marks'].fillna(0)
df['City'] = df['City'].fillna('Unknown')
df

    Name Department  Marks  Attendance       City
0   Amit         CS   85.0        90.0  Ahmedabad
1  Priya         IT   92.0         NaN      Surat
2  Rahul       None    0.0        85.0   Vadodara
3   Neha         CS   88.0         NaN    Unknown
4  Karan         IT   76.0        95.0     Rajkot

### 14. Fill Missing Values using Mean and Median

Create a DataFrame containing missing numerical values. Fill missing values in the `Marks` column using the mean and demonstrate filling another numerical column using the median.

In [43]:
data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Karan'],
    'Department': ['CS', 'IT', None, 'CS', 'IT'],
    'Marks': [85, 92, np.nan, 88, 76],
    'Attendance': [90, None, 85, np.nan, 95],
    'City': ['Ahmedabad', 'Surat', 'Vadodara', None, 'Rajkot']
}

df = pd.DataFrame(data)

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].median())

print(df)

    Name Department  Marks  Attendance       City
0   Amit         CS  85.00        90.0  Ahmedabad
1  Priya         IT  92.00        90.0      Surat
2  Rahul       None  85.25        85.0   Vadodara
3   Neha         CS  88.00        90.0       None
4  Karan         IT  76.00        95.0     Rajkot

### 15. Fill Missing Categorical Values using Mode

Create a DataFrame containing missing values in a categorical column such as `City` or `Department`. Fill the missing values using the mode of that column.

In [51]:
data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Neha', 'Karan'],
    'Department': ['CS', 'IT', None, 'CS', None],
    'Marks': [85, 92, np.nan, 88, 76],
    'Attendance': [90, None, 85, np.nan, 95],
    'City': ['Ahmedabad', None, 'Vadodara', None, 'Rajkot']
}

df = pd.DataFrame(data)

df["City"] = df["City"].fillna(df["City"].mode()[0])

df

    Name Department  Marks  Attendance       City
0   Amit         CS   85.0        90.0  Ahmedabad
1  Priya         IT   92.0         NaN  Ahmedabad
2  Rahul       None    NaN        85.0   Vadodara
3   Neha         CS   88.0         NaN  Ahmedabad
4  Karan       None   76.0        95.0     Rajkot

### 16. Forward Fill and Backward Fill

Create a time-series-like DataFrame containing missing values. Demonstrate forward filling using `ffill()` and backward filling using `bfill()`. Observe the difference between the two methods.

In [52]:
df

    Name Department  Marks  Attendance       City
0   Amit         CS   85.0        90.0  Ahmedabad
1  Priya         IT   92.0         NaN  Ahmedabad
2  Rahul       None    NaN        85.0   Vadodara
3   Neha         CS   88.0         NaN  Ahmedabad
4  Karan       None   76.0        95.0     Rajkot

### 17. Groupby - Basic Grouping

Create a DataFrame containing `Department`, `Student`, and `Marks`. Group the data by `Department` and calculate the average marks for each department.

### 18. Groupby with Multiple Aggregations

Using a student DataFrame, group the records by `Department` and calculate the minimum, maximum, mean, and count of `Marks` for each department.

### 19. Groupby with Multiple Columns

Create a DataFrame containing `Department`, `Semester`, `Student`, and `Marks`. Group the data by both `Department` and `Semester` and calculate the average marks.

### 20. Named Aggregation using agg()

Using a student DataFrame, group the data by `Department` and use `agg()` with named aggregation to calculate `Maximum_Marks`, `Minimum_Marks`, and `Average_Marks`.

### 21. Groupby and Count Records

Create a DataFrame containing student details and departments. Use `groupby()` to count the number of students in each department. Also calculate the number of unique cities for each department.

### 22. Groupby after Handling Missing Data

Create a DataFrame containing `Department`, `Marks`, and `City` with missing values. Handle the missing marks appropriately and then group the data by department to calculate average marks.